// Batch comparison exports: one file covering many A↔B pairs.
// The HTML report reuses the single-report per-page renderers.

import type { CompareSummary, PageComparison } from '../types/compare';
import { summaryPageDiffers } from './changes';
import {
  REPORT_CSS,
  download,
  escapeHtml,
  judgePage,
  pct,
  reportPageDetail,
  reportPageRows,
  stamp,
  type ExportThresholds,
} from './exportReport';

export interface BatchPairExport {
  index: number; // 1-based
  aName: string;
  bName: string;
  summary: CompareSummary;
  pageCache: Record<number, PageComparison>;
}

function pairVerdict(summary: CompareSummary, t: ExportThresholds): boolean {
  return summary.pages.every((p) => judgePage(p, t));
}

function worst(summary: CompareSummary) {
  const nonMissing = summary.pages.filter((p) => !p.missing);
  const worstContent = nonMissing.length ? Math.min(...nonMissing.map((p) => p.contentMatch)) : null;
  const worstPixels = nonMissing.length ? Math.max(...nonMissing.map((p) => p.pixelRatio)) : null;
  const worstOffsetIn = nonMissing.length ? Math.max(...nonMissing.map((p) => p.maxOffset / p.pxPerInch)) : null;
  const differing = summary.pages.filter((p) => summaryPageDiffers(p)).length;
  return { worstContent, worstPixels, worstOffsetIn, differing };
}

// ── HTML ──────────────────────────────────────────────────────────────
export async function exportBatchHtml(
  pairs: BatchPairExport[],
  thresholds: ExportThresholds,
  onProgress?: (done: number, total: number) => void,
) {
  const now = new Date();
  const overallPass = pairs.every((p) => pairVerdict(p.summary, thresholds));
  const passCount = pairs.filter((p) => pairVerdict(p.summary, thresholds)).length;

  const overviewRows = pairs
    .map((p) => {
      const pass = pairVerdict(p.summary, thresholds);
      const w = worst(p.summary);
      return `<tr class="${pass ? 'pass' : 'fail'}">
        <td><a class="jump" href="#pair-${p.index}">${p.index}</a></td>
        <td>${escapeHtml(p.aName)}</td>
        <td>${escapeHtml(p.bName)}</td>
        <td>${p.summary.pages.length}</td>
        <td>${w.differing}</td>
        <td>${w.worstContent == null ? '—' : pct(w.worstContent)}</td>
        <td>${w.worstPixels == null ? '—' : pct(w.worstPixels)}</td>
        <td>${w.worstOffsetIn == null ? '—' : w.worstOffsetIn.toFixed(2) + '″'}</td>
        <td class="result">${pass ? '✓ PASS' : '✗ FAIL'}</td>
      </tr>`;
    })
    .join('\n');

  const pairSections: string[] = [];
  for (let i = 0; i < pairs.length; i++) {
    const p = pairs[i];
    const pass = pairVerdict(p.summary, thresholds);
    const detail = await reportPageDetail(p.summary, p.pageCache, thresholds);
    pairSections.push(`<div class="pair-block" id="pair-${p.index}">
      <h2>Pair ${p.index}: ${escapeHtml(p.aName)} &nbsp;vs&nbsp; ${escapeHtml(p.bName)} <span class="chip ${pass ? 'pass' : 'fail'}">${pass ? 'PASS' : 'FAIL'}</span></h2>
      <p class="sub">A: ${p.summary.pageCountA} pages · B: ${p.summary.pageCountB} pages</p>
      <table>
        <thead><tr><th>Page</th><th>Content match</th><th>Pixels different</th><th>Max offset</th><th>Result</th></tr></thead>
        <tbody>${reportPageRows(p.summary, thresholds)}</tbody>
      </table>
      ${detail}
    </div>`);
    onProgress?.(i + 1, pairs.length);
  }

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Batch PDF Comparison Report</title>
<style>${REPORT_CSS}</style>
</head>
<body>
  <h1>Batch PDF Comparison Report</h1>
  <p class="sub">${pairs.length} comparison${pairs.length === 1 ? '' : 's'} · generated ${now.toLocaleString()}</p>
  <div class="verdict ${overallPass ? 'pass' : 'fail'}">${overallPass ? '✓ ALL PAIRS PASS' : '✗ SOME PAIRS FAIL'} — ${passCount}/${pairs.length}</div>
  <div class="meta-grid">
    <div><span>Thresholds:</span> <b>content ≥ ${thresholds.contentPct}% · pixels ≤ ${thresholds.pixelPct}% · offset ≤ ${thresholds.offsetIn}″</b></div>
  </div>
  <h2>Overview</h2>
  <table>
    <thead><tr><th>#</th><th>Side A</th><th>Side B</th><th>Pages</th><th>Differing</th><th>Worst content</th><th>Worst pixels</th><th>Worst offset</th><th>Result</th></tr></thead>
    <tbody>${overviewRows}</tbody>
  </table>
  ${pairSections.join('\n')}
  <footer>Generated by PDF Comparison Suite · Batch compare · ${now.toLocaleString()}</footer>
</body>
</html>`;

  download(`pdf-batch-report-${stamp()}.html`, html, 'text/html');
}

// ── JSON ──────────────────────────────────────────────────────────────
export function exportBatchJson(pairs: BatchPairExport[], thresholds: ExportThresholds) {
  const payload = {
    generatedAt: new Date().toISOString(),
    thresholds,
    overall: pairs.every((p) => pairVerdict(p.summary, thresholds)) ? 'PASS' : 'FAIL',
    pairCount: pairs.length,
    pairs: pairs.map((p) => ({
      index: p.index,
      sideA: p.aName,
      sideB: p.bName,
      pageCountA: p.summary.pageCountA,
      pageCountB: p.summary.pageCountB,
      verdict: pairVerdict(p.summary, thresholds) ? 'PASS' : 'FAIL',
      pages: p.summary.pages.map((pg) => ({
        page: pg.pageIndex + 1,
        contentMatch: pg.contentMatch,
        pixelRatio: pg.pixelRatio,
        maxOffsetInches: Number((pg.maxOffset / pg.pxPerInch).toFixed(3)),
        missing: pg.missing,
        pass: judgePage(pg, thresholds),
      })),
    })),
  };
  download(`pdf-batch-${stamp()}.json`, JSON.stringify(payload, null, 2), 'application/json');
}

// ── CSV ───────────────────────────────────────────────────────────────
export function exportBatchCsv(pairs: BatchPairExport[], thresholds: ExportThresholds) {
  const header = ['Pair', 'SideA', 'SideB', 'Page', 'ContentMatch%', 'PixelsDifferent%', 'MaxOffsetInches', 'Missing', 'Result'];
  const esc = (s: string) => (/[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);
  const rows: string[][] = [];
  for (const p of pairs) {
    for (const pg of p.summary.pages) {
      rows.push([
        String(p.index),
        esc(p.aName),
        esc(p.bName),
        String(pg.pageIndex + 1),
        (pg.contentMatch * 100).toFixed(2),
        (pg.pixelRatio * 100).toFixed(2),
        (pg.maxOffset / pg.pxPerInch).toFixed(3),
        pg.missing ? 'yes' : 'no',
        judgePage(pg, thresholds) ? 'PASS' : 'FAIL',
      ]);
    }
  }
  const csv = [header, ...rows].map((r) => r.join(',')).join('\r\n');
  download(`pdf-batch-${stamp()}.csv`, csv, 'text/csv');
}

export { pairVerdict, worst };
