// Visual HTML report.
//
// Built from the app's OWN exporters (REPORT_CSS, reportPageRows, reportPageDetail) so the
// output is the same report the app produces — same layout, same annotated pages, same
// heatmap with before→after labels. The only difference is delivery: the app hands the
// string to download(), the CLI writes it with fs.

import fs from 'node:fs';
import path from 'node:path';

import { REPORT_CSS, escapeHtml, pct, reportPageDetail, reportPageRows } from '../platform/engine.js';
import type { PairResult, RunContext } from './types.js';

export async function writeHtmlReport(
  results: PairResult[],
  ctx: RunContext,
  outDir: string,
  onProgress?: (done: number, total: number) => void,
): Promise<string> {
  const passCount = results.filter((r) => r.pass).length;
  const overall = passCount === results.length;

  const overviewRows = results
    .map((r) => {
      const nonMissing = r.summary.pages.filter((p) => !p.missing);
      const worstContent = nonMissing.length ? Math.min(...nonMissing.map((p) => p.contentMatch)) : null;
      const worstPixels = nonMissing.length ? Math.max(...nonMissing.map((p) => p.pixelRatio)) : null;
      const worstOffset = nonMissing.length
        ? Math.max(...nonMissing.map((p) => p.maxOffset / p.pxPerInch))
        : null;
      const skipped = r.pageVerdicts.filter((v) => v.skipped).length;
      return `<tr class="${r.pass ? 'pass' : 'fail'}">
        <td><a class="jump" href="#pair-${escapeHtml(r.pair.id)}">${escapeHtml(r.pair.id)}</a></td>
        <td>${escapeHtml(r.pair.name)}</td>
        <td>${escapeHtml(r.pair.referenceRel)}</td>
        <td>${escapeHtml(r.pair.candidateRel)}</td>
        <td>${r.summary.pages.length}${skipped ? ` <span title="skipped pages">(−${skipped})</span>` : ''}</td>
        <td>${worstContent == null ? '—' : pct(worstContent)}</td>
        <td>${worstPixels == null ? '—' : pct(worstPixels)}</td>
        <td>${worstOffset == null ? '—' : worstOffset.toFixed(2) + '″'}</td>
        <td class="result">${r.pass ? '✓ PASS' : '✗ FAIL'}</td>
      </tr>`;
    })
    .join('\n');

  const sections: string[] = [];
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    const t = r.pair.thresholds;

    if (r.error) {
      sections.push(`<div class="pair-block" id="pair-${escapeHtml(r.pair.id)}">
        <h2>${escapeHtml(r.pair.name)} <span class="chip fail">ERROR</span></h2>
        <p class="sub">${escapeHtml(r.error)}</p>
      </div>`);
      onProgress?.(i + 1, results.length);
      continue;
    }

    const detail = await reportPageDetail(r.summary, r.pageCache, t);
    const skipNote = r.pair.skipPages.length
      ? `<p class="sub">Pages excluded from the verdict: ${r.pair.skipPages.join(', ')}</p>`
      : '';

    sections.push(`<div class="pair-block" id="pair-${escapeHtml(r.pair.id)}">
      <h2>${escapeHtml(r.pair.name)} <span class="chip ${r.pass ? 'pass' : 'fail'}">${r.pass ? 'PASS' : 'FAIL'}</span></h2>
      <p class="sub">
        <b>${escapeHtml(r.pair.referenceRel)}</b> &nbsp;vs&nbsp; <b>${escapeHtml(r.pair.candidateRel)}</b>
        · A: ${r.summary.pageCountA} pages · B: ${r.summary.pageCountB} pages
        · thresholds content ≥ ${t.contentPct}% · pixels ≤ ${t.pixelPct}% · offset ≤ ${t.offsetIn}″
      </p>
      ${skipNote}
      <table>
        <thead><tr><th>Page</th><th>Content match</th><th>Pixels different</th><th>Max offset</th><th>Result</th></tr></thead>
        <tbody>${reportPageRows(r.summary, t)}</tbody>
      </table>
      ${detail}
    </div>`);

    onProgress?.(i + 1, results.length);
  }

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>PDF Comparison Report — ${results.length} pair${results.length === 1 ? '' : 's'}</title>
<style>${REPORT_CSS}</style>
</head>
<body>
  <h1>PDF Comparison Report</h1>
  <p class="sub">${results.length} pair${results.length === 1 ? '' : 's'} · generated ${ctx.generatedAt.toLocaleString()}</p>
  <div class="verdict ${overall ? 'pass' : 'fail'}">${overall ? '✓ ALL PAIRS PASS' : '✗ SOME PAIRS FAIL'} — ${passCount}/${results.length}</div>
  <div class="meta-grid">
    <div><span>Reference:</span> <b>${escapeHtml(ctx.referenceDir)}</b></div>
    <div><span>Candidate:</span> <b>${escapeHtml(ctx.candidateDir)}</b></div>
    <div><span>Default thresholds:</span> <b>${escapeHtml(ctx.thresholdsLabel)}</b></div>
    <div><span>Generated:</span> <b>${ctx.generatedAt.toLocaleString()}</b></div>
  </div>
  <h2>Overview</h2>
  <table>
    <thead><tr><th>ID</th><th>Name</th><th>Reference</th><th>Candidate</th><th>Pages</th><th>Worst content</th><th>Worst pixels</th><th>Worst offset</th><th>Result</th></tr></thead>
    <tbody>${overviewRows}</tbody>
  </table>
  ${sections.join('\n')}
  <footer>Generated by PDF Comparison Suite · CLI · ${ctx.generatedAt.toLocaleString()}</footer>
</body>
</html>`;

  const file = path.join(outDir, 'report.html');
  fs.writeFileSync(file, html);
  return file;
}
